name: Model Training Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: Why to run this?
        required: false
        default: running CT

jobs:
  continuous_training:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r src/requirements.txt  # Instalar desde el directorio src

          echo "Dependencies Installed"

      - name: Run Python Scripts
        run: |
          source venv/bin/activate  # Activar entorno virtual
          python src/get_last_file.py  # Ejecutar script1 desde src
          python src/convert.py  # Ejecutar script2 desde src
          python src/tracker.py  # Ejecutar script3 desde src
          python src/prepare.py  # Ejecutar script3 desde src
          python src/train_model.py  # Ejecutar script3 desde src

          echo "Scripts Completed"
