name: Model Training Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: Why to run this?
        required: false
        default: running CT

jobs:
  continuous_training:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Verify requirements.txt
        run: |
          if [ -f "requirements.txt" ]; then
            echo "requirements.txt found."
          elif [ -f "src/requirements.txt" ]; then
            echo "src/requirements.txt found."
            mv src/requirements.txt requirements.txt
          else
            echo "Error: requirements.txt not found."
            exit 1  # Salir con un código de error para detener el flujo de trabajo
          fi

      - name: Install dependencies
        if: success()  # Ejecutar solo si el paso anterior fue exitoso
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r requirements.txt  # Utiliza el archivo correcto

          echo "Training Completed"
