name: Model Training Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: Why to run this?
        required: false
        default: running CT

jobs:
  continuous_training:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Verify directory contents
        run: |
          ls -la  # Listar contenido del directorio para verificar la estructura
          find . -name "requirements.txt"  # Buscar el archivo en el directorio

      - name: Install dependencies
        run: |
          cd src  # Cambiar al directorio correcto si es necesario
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r requirements.txt  # Acceder al archivo correcto

          echo "Training Completed"
