name: Model Training Workflow  # Nombre significativo para tu flujo de trabajo

on:
  push:
    branches:
      - main  # Cambia según tu rama principal
  schedule:
    - cron: '0 */6 * * *'  # Ejecutar cada 6 horas
  workflow_dispatch:
    inputs:
      reason:
        description: Why to run this?
        required: false
        default: running CT

jobs:
  continuous_training:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Train model
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r src/requirements.txt

          echo "Training Completed"
